"""Add Online Assessment question-bank tables (Category, Question, QuestionOption)

Hand-written (not autogenerated) on purpose: this migration creates ONLY the
three new assessment_* tables. It must never touch the pre-existing
users / interview_sessions / questions / soft_skills_metrics / token_usage
tables, which were created ad hoc via Base.metadata.create_all() and are not
otherwise managed by Alembic.

Revision ID: 0001_assessment_bank
Revises:
Create Date: 2026-08-22
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0001_assessment_bank"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "assessment_categories",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.UniqueConstraint("name", name="uq_assessment_categories_name"),
        sa.UniqueConstraint("slug", name="uq_assessment_categories_slug"),
    )
    op.create_index(
        "ix_assessment_categories_slug", "assessment_categories", ["slug"]
    )

    op.create_table(
        "assessment_questions",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("category_id", sa.String(length=36), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("difficulty", sa.String(length=20), nullable=False),
        sa.Column("external_ref", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["assessment_categories.id"],
            name="fk_assessment_questions_category_id",
        ),
        sa.UniqueConstraint("external_ref", name="uq_assessment_questions_external_ref"),
    )
    op.create_index(
        "ix_assessment_questions_category_id", "assessment_questions", ["category_id"]
    )
    op.create_index(
        "ix_assessment_questions_external_ref", "assessment_questions", ["external_ref"]
    )

    op.create_table(
        "assessment_question_options",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("option_text", sa.Text(), nullable=False),
        sa.Column("option_index", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"], ["assessment_questions.id"],
            name="fk_assessment_question_options_question_id",
        ),
        sa.UniqueConstraint(
            "question_id", "option_index", name="uq_assessment_option_question_index"
        ),
    )
    op.create_index(
        "ix_assessment_question_options_question_id",
        "assessment_question_options",
        ["question_id"],
    )


def downgrade() -> None:
    # Reverse dependency order. Only ever drops the 3 tables this migration
    # created — never touches any pre-existing application table.
    op.drop_index(
        "ix_assessment_question_options_question_id",
        table_name="assessment_question_options",
    )
    op.drop_table("assessment_question_options")

    op.drop_index("ix_assessment_questions_external_ref", table_name="assessment_questions")
    op.drop_index("ix_assessment_questions_category_id", table_name="assessment_questions")
    op.drop_table("assessment_questions")

    op.drop_index("ix_assessment_categories_slug", table_name="assessment_categories")
    op.drop_table("assessment_categories")
