"""Add Online Assessment attempt-tracking tables (Attempt, AttemptAnswer)

Hand-written (not autogenerated) for the same reason as 0001: this
migration creates ONLY the two new assessment_attempts /
assessment_attempt_answers tables. It must never touch the pre-existing
users / interview_sessions / questions / soft_skills_metrics / token_usage
tables, nor the Phase-1 assessment_categories / assessment_questions /
assessment_question_options tables created by 0001.

Revision ID: 0002_assessment_attempts
Revises: 0001_assessment_bank
Create Date: 2026-08-23
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0002_assessment_attempts"
down_revision = "0001_assessment_bank"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "assessment_attempts",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("category_slug", sa.String(length=255), nullable=True),
        sa.Column("difficulty", sa.String(length=20), nullable=True),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("question_ids", sa.JSON(), nullable=False),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("correct_answers", sa.Integer(), nullable=False),
        sa.Column("wrong_answers", sa.Integer(), nullable=False),
        sa.Column("unanswered_answers", sa.Integer(), nullable=False),
        sa.Column("score_percentage", sa.Float(), nullable=False),
        sa.Column("accuracy_percentage", sa.Float(), nullable=False),
        sa.Column("time_taken_seconds", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
    )

    op.create_table(
        "assessment_attempt_answers",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=False),
        sa.Column("selected_option_id", sa.String(length=36), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"], ["assessment_attempts.id"],
            name="fk_assessment_attempt_answers_attempt_id",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["assessment_questions.id"],
            name="fk_assessment_attempt_answers_question_id",
        ),
        sa.UniqueConstraint(
            "attempt_id", "question_id", name="uq_attempt_answer_attempt_question"
        ),
    )
    op.create_index(
        "ix_assessment_attempt_answers_attempt_id",
        "assessment_attempt_answers",
        ["attempt_id"],
    )
    op.create_index(
        "ix_assessment_attempt_answers_question_id",
        "assessment_attempt_answers",
        ["question_id"],
    )


def downgrade() -> None:
    # Reverse dependency order. Only ever drops the 2 tables this migration
    # created — never touches any pre-existing or Phase-1 table.
    op.drop_index(
        "ix_assessment_attempt_answers_question_id",
        table_name="assessment_attempt_answers",
    )
    op.drop_index(
        "ix_assessment_attempt_answers_attempt_id",
        table_name="assessment_attempt_answers",
    )
    op.drop_table("assessment_attempt_answers")
    op.drop_table("assessment_attempts")
