"""Add is_active flag to assessment_questions (V2.4 admin question-bank mgmt)

Hand-written (not autogenerated), same convention as 0001/0002: touches
ONLY the assessment_questions table, adding a single non-nullable Boolean
column with a server-side default so existing rows backfill to true
(visible/selectable) without a separate data-migration step.

Revision ID: 0003_assessment_active_flag
Revises: 0002_assessment_attempts
Create Date: 2026-08-23
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0003_assessment_active_flag"
down_revision = "0002_assessment_attempts"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "assessment_questions",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )


def downgrade() -> None:
    op.drop_column("assessment_questions", "is_active")
